package dao;

import model.Appointment;
import model.DentistProfile;
import model.Patient;
import model.Treatment;
import org.junit.Before;
import org.junit.Test;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

import static org.junit.Assert.*;

/**
 * Unit tests for AppointmentDAO, CheckDentistAvailability stored function,
 * and trg_before_insert_appointment auto-number trigger.
 *
 * @author Student
 */
public class AppointmentDAOTest {
    private AppointmentDAO appointmentDAO;
    private DentistDAO dentistDAO;
    private PatientDAO patientDAO;
    private TreatmentDAO treatmentDAO;

    @Before
    public void setUp() {
        appointmentDAO = new AppointmentDAOImpl();
        dentistDAO = new DentistDAOImpl();
        patientDAO = new PatientDAOImpl();
        treatmentDAO = new TreatmentDAOImpl();
    }

    @Test
    public void testCheckDentistAvailabilityStoredFunction() {
        // Dynamically find any active scheduled appointment
        List<Appointment> allAppts = appointmentDAO.findAll();
        Appointment activeAppt = null;
        for (Appointment a : allAppts) {
            if ("SCHEDULED".equalsIgnoreCase(a.getStatus()) || "IN PROGRESS".equalsIgnoreCase(a.getStatus())) {
                activeAppt = a;
                break;
            }
        }

        if (activeAppt != null) {
            boolean availableOccupiedSlot = appointmentDAO.isDentistAvailable(
                    activeAppt.getDentist().getId(),
                    activeAppt.getAppointmentDate(),
                    activeAppt.getAppointmentTime()
            );
            assertFalse("Active scheduled slot should be occupied (stored function returns 0)", availableOccupiedSlot);
        }

        // Test with Dr. Silva on an unoccupied future slot
        LocalDate futureDate = LocalDate.now().plusMonths(8);
        LocalTime freeTime = LocalTime.of(15, 30);
        boolean availableFreeSlot = appointmentDAO.isDentistAvailable(1, futureDate, freeTime);
        assertTrue("Future unbooked slot should be available (stored function returns 1)", availableFreeSlot);
    }

    @Test
    public void testAppointmentCreationAndTriggerAutoNumbering() {
        Patient patient = patientDAO.findById(1);
        DentistProfile dentist = dentistDAO.findById(2);
        Treatment treatment = treatmentDAO.findById(1);

        assertNotNull("Patient 1 must exist", patient);
        assertNotNull("Dentist 2 must exist", dentist);
        assertNotNull("Treatment 1 must exist", treatment);

        LocalDate apptDate = LocalDate.now().plusDays((int) (System.currentTimeMillis() % 1000) + 50);
        LocalTime apptTime = LocalTime.of(16, 0);

        // Ensure slot is free initially
        assertTrue("Target slot should be free initially", appointmentDAO.isDentistAvailable(dentist.getId(), apptDate, apptTime));

        Appointment newAppt = new Appointment();
        newAppt.setPatient(patient);
        newAppt.setDentist(dentist);
        newAppt.setTreatment(treatment);
        newAppt.setAppointmentDate(apptDate);
        newAppt.setAppointmentTime(apptTime);
        newAppt.setStatus("SCHEDULED");
        newAppt.setNotes("TDD Unit Test Booking");

        Appointment created = appointmentDAO.create(newAppt);
        assertNotNull("Created appointment should not be null", created);
        assertTrue("Created appointment must have generated ID", created.getId() > 0);

        // Verify that MySQL BEFORE INSERT trigger populated the appointment_number
        assertNotNull("Appointment number must be generated by trigger", created.getAppointmentNumber());
        assertTrue("Appointment number must match APT-YYYY-XXXX format: " + created.getAppointmentNumber(),
                created.getAppointmentNumber().matches("^APT-\\d{4}-\\d{4}$"));

        // Slot must now be occupied via stored function
        boolean availableAfterBooking = appointmentDAO.isDentistAvailable(dentist.getId(), apptDate, apptTime);
        assertFalse("Slot must now be occupied after booking", availableAfterBooking);

        // Verify lookup by appointment number
        Appointment fetched = appointmentDAO.findByAppointmentNumber(created.getAppointmentNumber());
        assertNotNull("Should fetch appointment by generated number", fetched);
        assertEquals(created.getId(), fetched.getId());
        assertEquals(patient.getName(), fetched.getPatient().getName());
        assertEquals(dentist.getFullName(), fetched.getDentist().getFullName());
        assertEquals(treatment.getType(), fetched.getTreatment().getType());
    }
}
